# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Sanchaara"
description: > # this means to ignore newlines until "email:"
   Namma Payana..

email: me@sandeepraju.in # replace this with sanchaara group email address.

# Blog logo
# logo: "/assets/images/df_logo.jpg"
# Blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Team Sanchaara'
author: 'Team Sanchaara'
author_image: "/assets/images/girl.png"

paginate: 5

url: "http://sanchaara.in" # the base hostname & protocol for your site
baseurl: ""

# Url configuration
permalink: pretty

# social icons and sharing options
# social:
#   - icon:	twitter
#     url:	https://twitter.com/by2kaapi/
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

# - icon:	github
#   url:	https://github.com/sandeepraju/sanchaara.in/
#   desc:	Fork me on github
#   share_url:
#   share_title:
#   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

gems:
  - jemoji
